### PR TITLE
UI bug fix

### PR DESCRIPTION
**Pull request by amr3k**
## This is a fix for #4 
The iframe was not applying theme on load until the user switches theme.
Now I added an event listener that post a message to `iframe` window to set the desired theme.

### A live demo showing this exists in my blog.

- [Before](https://computly-lma0zq671-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)
- [After](https://computly-evnetkpni-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)

**Hint**
1. Switch to dark theme in footer
2. Refresh the page **or** navigate to any other page
3. Return to any blog post and scroll down to comments.
4. See if the dark theme is automatically applied.

Please hit `Ctrl`+`Shift`+`R` when you visit the second link to clear browser cache.

### CODE REVIEW

**Comment by shinokada** [comment]
I tested it but it is not working.
After pulling your commit, I created another page about.svelte.
In the index.svelte, I toggled the theme, went to the about page, then go back to the index again. Then theme didn't keep the toggled theme.

**Comment by amr3k** [comment]
Sorry @shinokada  I made a mistake and force-pushed to my fork after trying to sign my commits, but it signed all commits (including yours) with my own key.
So I deleted my fork and going to re-fork again and make the changes one more time and do a pull request.

As for your comment, the theme consistency is the responsibility of the developer .. not this package.

In my blog I'm using a store to save the theme, before I used this package, you can see the theme applies to all elements.
So by adding utterances, I'm syncing its theme with the global theme so navigating to other pages will apply to both the website and the utterances iframe.

**Comment by shinokada** [comment]
Aha. Now I can see how you are approaching the issue. And it is good to sync its theme with the global theme.

My approach is a different. I treated them as different theme, one for global theme and one for Utterances theme.

If a developer's website doesn't have a theme switcher or a dark mode, then a visiter can select one of the Utterances themes from github-light, github-dark, etc from a dropdown. 
You can see it what I wanted to achieve at the bottom of this [example](https://svelte-utterances.vercel.app/dynamic-theme).
 
I think the theme consistency can be achieve by using Svelte Store and localStorage. And it can be integrated to this library. 

I will be happy to add different components, UtterancesSwitch that you are creating to this repo.
Again thank you for your work. I appreciate it.

**Comment by amr3k** [comment]
Well I'd like to express my thoughts on this.

1. This change would take control from the developer, which was theirs before adding dynamic theme support ... the developer would have to set the theme manually.
2. If a developer wants to give users the ability to choose comments theme, then they should be responsible for implementing this feature by making a select menu in the style they like that would suit the website theme, and add another store for it and sync that store with utternaces, they also may want to set defaults for both.
3. This also is based on the assumption that users would need a separate theme for comments, but in reality I don't think this is the case.
4. This change would make users have to switch the theme twice, once for the website and the second for the comments, I believe this is not good UX.
5. If a website has an auto theme based on `prefers-color-scheme`, and the user's device is on dark mode, and visits the website for the first time, the website would be dark but comments would be light which ruins UI, and vice versa, if a website doesn't have themes (light mode only), and we decided to make utterances based on `prefers-color-scheme` it will load in dark mode as default which again would not be consistent with the website!! we really don't know what the developer might want how their website should look like.

**Comment by shinokada** [comment]
@416d72 You made good points. I like #4 and #5.
This discussion leads to what this package should provide for the developer relating to theme changes.
I'm looking forwards to your next pull request.

**Pull request closed without merging**
