### PR TITLE
UI bug fix (2️⃣)

### PR DESCRIPTION
**Pull request by amr3k**
> 2nd attempt because my first attempt caused a [unwanted chages](https://github.com/shinokada/svelte-utterances/pull/9#issuecomment-1095794936)
## This is a fix for #4 
The iframe was not applying theme on load until the user switches theme.
Now I added an event listener that post a message to `iframe` window to set the desired theme.

### A live demo showing this exists in my blog.

- [Before](https://computly-lma0zq671-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)
- [After](https://computly-evnetkpni-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)

**Hint**
1. Switch to dark theme in footer
2. Refresh the page **or** navigate to any other page
3. Return to any blog post and scroll down to comments.
4. See if the dark theme is automatically applied.

Please hit `Ctrl`+`Shift`+`R` when you visit the second link to clear browser cache.

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks for the PR.
I can't see why we need the `sendPostMessage` function. It works without it as well.
Can you explain the reason behind? Thanks.

**Comment by amr3k** [comment]
@shinokada , sure, the `sendPostMessage` function is called after the component is mounted.
This is a fix for #4 where if you set the theme to dark mode, and navigated to another page then returned back, you'll see utterances went back to light mode despite the whole site is in dark.

The solution I made is to call that function after mount, and also check for theme changes with reactivity so users would be able to dynamically switch utterances theme with the website theme.

This function has to exist instead of writing `postMessage` inline, to be able to use recursion as `iFrame` may take some time until it loads.

Please take a look at this:
> ### A live demo showing this exists in my blog.

> - [Before](https://computly-lma0zq671-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)
> - [After](https://computly-evnetkpni-a3k.vercel.app/blog/build-a-simple-telegram-bot-with-fastapi)

> **Hint**
> 1. Switch to dark theme in footer
> 2. Refresh the page **or** navigate to any other page
> 3. Return to any blog post and scroll down to comments.
> 4. See if the dark theme is automatically applied.

> Please hit `Ctrl`+`Shift`+`R` when you visit the second link to clear browser cache.

**Comment by shinokada** [comment]
Thanks. I can see it in action on your website. It looks good.
Is it possible to add a simple example in the `src/routes` directory to show how it works?
With my current [demo site setting](https://svelte-utterances.vercel.app/), I don't think it works.

**Comment by amr3k** [comment]
> Thanks. I can see it in action on your website. It looks good. Is it possible to add a simple example in the `src/routes` directory to show how it works?

No problem, this would have to be a basic sveltekit-based routing and a theme store that utilizes `localStorage` for persistence, I can do it tomorrow (It's 3 A.M here 🙃)

> With my current [demo site setting](https://svelte-utterances.vercel.app/), I don't think it works.

Because you are not using a store, so theme changes don't persist.

**Comment by shinokada** [comment]
If you can add a short explanation, it would be very helpful for users.

**Comment by amr3k** [comment]
> With my current [demo site setting](https://svelte-utterances.vercel.app/), I don't think it works.

I just looked into the demo website once more, and I was wrong, the reason is because you are using an old version of this package, which doesn't include the fix I made in this PR aka `sendPostMessage` function.
If you accepted this PR and merged it with demo-site branch, you'll see the new version running.

**Comment by shinokada** [comment]
I have done it locally and it doesn't work with my demo-site setup.

**Comment by amr3k** [comment]
Are you using a store & sync it with localStorage?

Also  are you using Firefox? Because I saw some issue with it that didn't happen in Chrome

**Comment by amr3k** [comment]
This is working proof of my modifications

Please take a look at the [newest preview](https://svelte-utterances-2d1nd52vn-okadashinichi.vercel.app/)

Set the theme to dark and refresh the page

**Comment by shinokada** [comment]
[Tested](https://svelte-utterances-2d1nd52vn-okadashinichi.vercel.app/) on FF and Brave(Chrome).

1. First load
image

2. Click the darkmode
image

3. Refreshed. It keeps the dark mode but Utterances goes back to light theme.
image

And on Brave(Chrome) behaves strange toggling the dark mode. The Utterances theme is opposite of the site theme.

**Comment by amr3k** [comment]
This is weird, I'm going to do more investigation

**Comment by amr3k** [comment]
Just looked it up again and fixed that bug.

Let me know if it works.

**Comment by shinokada** [comment]
Thank you for the PR. I will look into it shortly.

**Comment by amr3k** [comment]
@shinokada  Please review this PR

**Comment by shinokada** [comment]
Sorry for the delay.
This is what you have, [demo](https://svelte-utterances-gd7vv44d3-okadashinichi.vercel.app/). 

Is it possible to add dark mode as you did it [before](https://svelte-utterances-2d1nd52vn-okadashinichi.vercel.app/)?

Currently when I refresh the browser, the dark mode is gone.

It will be nice to have a practical example.

**Pull request closed without merging**
