### PR TITLE
Upgrade Sveltekit version & add localstorage support 

### PR DESCRIPTION
**Pull request by saweima12**
## Closes 
- #4 
- #11 
- #12 

## 📑 Description
- Upgrade Sveltekit to the latest version for easy testing
- Adjust routing with the latest version
- Add `theme` property to script element.
- Add `localstorage`  support to the example

### CODE REVIEW

**Comment by saweima12** [comment]
The build result

https://svelte-utterances-acuokw40j-saweima12.vercel.app/

**Comment by shinokada** [comment]
This is the error message:

image

**Comment by shinokada** [comment]
Can you upgrade Svelte/SvelteKit and create a PR?

**Comment by saweima12** [comment]
I will open a new PR to process this...

**Pull request closed without merging**
