### PR TITLE
Upgrade svelte & kit version

### PR DESCRIPTION
**Pull request by saweima12**
## 📑 Description

- Upgrade svelte & sveltekit to lastest version .
- Adjust the route to the latest rule.

## ✅ Checks

- [x] All the tests have passed

### CODE REVIEW

**Comment by saweima12** [comment]
well... this is weird.

It works on my fork via deploy.

Did vercel called `npm install`?

**Comment by shinokada** [comment]
image

**Comment by saweima12** [comment]
The latest sveltekit requires node version 16.9+

Can you set the node version of Vercel?

image

**Comment by shinokada** [comment]
I just update it to 16x.

**Comment by saweima12** [comment]
so... I need to send a new pull request ?

**Comment by shinokada** [comment]
Let me redeploy. Just a minute.

**Comment by saweima12** [comment]
OK thanks

**Comment by shinokada** [comment]
image
The deployment is success.

However, when I visit https://svelte-utterances-rat9b2z9s-okadashinichi.vercel.app/ and refreshing the page after toggle the theme, it doesn't keep the same theme.

**Comment by saweima12** [comment]
This PR is about sveltekit upgrade, not include fix

**Comment by saweima12** [comment]
I will send a new PR about that

**Comment by shinokada** [comment]
Ok. Thanks.

**Pull request merged**
